### ISSUE TITLE
these two records are different  SV records ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#101]
@tobiasrausch 
HI,author, 
the next two records are different  SV ?
how to convert these SV breakpoints into  Gene fusion format ?
like  :
chrA  POSA  GeneA  chrB  POSB   Gene B . 
and  these two SV records is for the same Gene fusion variants ??

chr6	117642092	BND00018142	C	C[chr1:154142762[	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=154142762;PE=1001;MAPQ=60;CT=3to5;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=1;CONSENSUS=GAGTAAGATTGACTTAAGGCTGACCACGTAACACAAGGCTCTCAAAACTCCAATACATGCCAAGTCACTACCAACTTCCTTTGGTGTACAGAAAAAGAGATT;CE=1.94802;RDRATIO=1.00106;SOMATIC	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-1000,0,-1000:10000:PASS:11286:22322:4829:3:3057:1207:3006:1300	0/0:0,-881.513,-1000:10000:PASS:8794:17894:4138:3:3137:1:2931:0

chr6	117642093	BND00018143	T	]chr1:154142761]T	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=154142761;PE=860;MAPQ=60;CT=5to3;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=1;CONSENSUS=AGAGTTTGACCCACTTTGCCTAGCTGTGGCATAGGACAGTGCACATGATATTTCTCCTCTCAAACACTGCCTCCAGGTCAACCAACCATGTTACCATCTATTCT;CE=1.96501;RDRATIO=1.00188;SOMATIC	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-1000,0,-1000:10000:PASS:11298:22331:4842:3:3057:865:3009:945	0/0:0,-879.428,-1000:10000:PASS:8811:17899:4150:3:3137:4:2924:0

**Comment by tobiasrausch** [comment]
This is a reciprocal translocation because the INFO:CT values are complementary (3to5 and 5to3) and the breakpoints coincide. Cancers also often harbor unbalanced translocations and then only one of the 2 SVs would be present. Delly follows the VCF Spec and VCFs can be annotated with VEP or SnpEff. Please consider subscribing to the Delly users group where these kind of usage questions are answered.

https://groups.google.com/forum/#!forum/delly-users
