### ISSUE TITLE
how to merge breakends into breakpoints of fusion gene ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#104]
HI,
   we know every fusion gene have two breakpoints , and for every breakpoint have two breakends that are recorded in the VCF file .
so I wanna know how to merge breakends into breakpoints to show two breakpoints for two fusion genes .

thank you in advance !

**Comment by tobiasrausch** [comment]
Fusion gene discovery is primarily done with RNA-Seq data because of greater depth and the requirement that fusion genes are expressed. Nevertheless, I think this could be indeed a useful extension for Delly to predict fusions from DNA and then corroborate these predictions by RNA (because predicting using RNA-Seq only has also its shortcomings). I am actually working on such a filtering mode and hope to have a beta version towards the summer along the lines:

delly filter -t fusion -v delly_dna.bcf -g GRChr37.gtf.gz -o dna_rna.bcf rna.bam

I flag this issue as an enhancement for the time being and let you know once this is ready.

**Comment by tobiasrausch** [comment]
This annotation of SVs is meanwhile available in [delly sansa](https://github.com/dellytools/sansa)
