### ISSUE TITLE
Cant build version 0.7.7

### ISSUE THREAD

**Issue by stevekm** [dellytools/delly#118]
I have been using the following command inside Docker to build Delly2 containers:

```
git clone --recursive https://github.com/dellytools/delly.git && \
cd delly && \
git checkout tags/v0.7.7 && \
git submodule update --recursive && \
make
```

Now, it suddenly does not work, and I get this error:

```
make[1]: Entering directory '/opt/delly/src/bcftools'
make[1]: Leaving directory '/opt/delly/src/bcftools'
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [.bcftools] Error 2
Makefile:52: recipe for target '.bcftools' failed
```

Did something in the repo for this release change?

Full Dockerfile:

```
# NGS580 container for Delly2
FROM stevekm/ngs580-nf:base

MAINTAINER Stephen M. Kelly

# ~~~~~ BASIC SETUP ~~~~~ #
RUN apt-get update && \
\
apt-get install -y git \
wget \
make \
gcc \
g++ \
libncurses5-dev \
zlib1g-dev \
libbz2-dev \
liblzma-dev 

# ~~~~~ DELLY2 ~~~~~ #
RUN cd /opt && \
git clone --recursive https://github.com/dellytools/delly.git && \
cd delly && \
git checkout tags/v0.7.7 && \
git submodule update --recursive && \
make
ENV PATH="/opt/delly/src:${PATH}"
```

**Comment by tobiasrausch** [comment]
I recently removed the boost and bcftools submodules because my impression is that most users get Delly from Bioconda or they use one of the statically linked binaries. You can still compile Delly from source but you now need to link against the system libraries. Here is an example Dockerfile:

https://github.com/dellytools/delly/blob/master/docker/Dockerfile

I am surprised that the checkout tags/v0.7.7 does not restore the submodules.
