### ISSUE TITLE
Will BND represents parital inversion?

### ISSUE THREAD

**Issue by lss1227** [dellytools/delly#135]
First, sorry for posting my question on github because I don't know why I cannot see my posts on google group.  I wonder if BND could represents parital inversion ? I know when one side of a translocation are in poor coverage or  low complexity region, Delly may only report the other good side.  What would happen if this happens to inversion ? How does Delly deal with this ? I didn't find answers about this. I'm sorry if this question has been asked before. Thank you very much for answers.

**Comment by tobiasrausch** [comment]
By design, one-sided events cannot be reported by Delly. Other methods sometimes just collect split-reads and then indeed only one side might be reported but for Delly always both breakpoints need to be present. All intra-chromosomal events are reported as DEL, DUP, or INV depending on the paired-end connection type. Only inter-chromosomal events are reported as BND (former TRA type of delly).
