### ISSUE TITLE
Warning: One library has a non-default paired-end layout!

### ISSUE THREAD

**Issue by maribuon** [dellytools/delly#137]
Hi!
I got the same warning as in issue #97. 
I have a pair-end, not mate-pair, library, trimmed with skewer and aligned with bwa-mem. All my reads are from the same read-group so removing them is not an option. How does the warning impact the results generated? It seems that I observe much less SVs that I would expect (I know the samples have altered CN in a region where I do not observe SVs). What can have caused the problem and how can I solve it?
Thanks for any help you can give me.
Mariana

**Comment by tobiasrausch** [comment]
That's a severe problem if your library has not the expected forward-reverse illumina paired-end layout. Could you please run [alfred](https://github.com/tobiasrausch/alfred) and send me the output json file?

./alfred qc -i -r <genome.fa> -f json -o qc.json.gz <alignment.bam>

You can also upload yourself the output json file to [https://gear.embl.de/alfred](https://gear.embl.de/alfred/) and look at the insert size distribution plot.

Thanks, Tobias

**Comment by maribuon** [comment]
[qc.json.gz](https://github.com/dellytools/delly/files/2470388/qc.json.gz)
Hi Tobias, thank you for the help. Here is the file. I did look at it on the alfred website. Very nice interface! But I must admit I don't understand very well what it means, if you can please help me interpreting it, I will very much appreciate.
Mariana

**Comment by tobiasrausch** [comment]
Hi,

You sequenced 2x150bp reads but your median insert size (fragment size) is only ~200bp. That is all your reads are partially overlapping, actually for almost 50% of your paired-ends you got completely overlapping reads. For such a library, paired-end mapping doesn't work and that's why delly cannot detect any SVs. These overlapping paired-ends are also no independent observations so you want to avoid these as much as possible for any type of variant calling. If you want to use delly then you need to trim the reads first to maybe 2x75bp reads and then remap.

Best, Tobias

**Comment by TendoLiu** [comment]
Hello, I came into the same issue. I have ten cfDNA samples coming from low-pass whole genome sequencing, 2x105, but average insert size is 130. What is weird is that 3 samples had this error but others not. Is there a interpretation from partially successful run?

Best,
Tendo

**Comment by tobiasrausch** [comment]
That's not unusual for cfDNA samples to have a very small insert size. Just try to adapt the sequencing length the next time otherwise you waste a lot of money for duplicate information. Something like 2x50bp or 2x75bp should be enough.
