### ISSUE TITLE
INS support

### ISSUE THREAD

**Issue by lslochov** [dellytools/delly#141]
Hi, I saw in an earlier post that there is no support for insertions in Delly, and I was curious if that feature has been implemented yet.

**Comment by tobiasrausch** [comment]
Yes, you can call insertions using

delly call -t INS ...

Please note that Delly calls insertion >=15bp because below that threshold short variant callers like FreeBayes are better. Delly also requires that the insertion is flanked by aligned sequences on both sides. That's fairly strict and limits the upper length of insertions to about ~100bp for 150bp reads. After quite some benchmarking we settled on this requirement otherwise the amount of false positive insertion predictions is rather large.
