### ISSUE TITLE
Binary Parallel delly build

### ISSUE THREAD

**Issue by molecules** [dellytools/delly#151]
Will there be a binary release built of the parallel delly 0.8.1? If not, are there issues preventing it (i.e. might it be a bad idea for me to try to build parallel delly 0.8.1 on my system)?

**Comment by tobiasrausch** [comment]
You can build a parallel delly. Nowadays, we rarely use the parallel version because the sample sizes are often >100 so processing a large batch of samples jointly with any variant caller is impossible. The typical workflow is a simple parallel processing of the samples in our cluster using multiple delly jobs (each as a single CPU job). That usually works best in scheduling the jobs and also on compute clouds such as AWS or Google Cloud.
