### ISSUE TITLE
coredump error

### ISSUE THREAD

**Issue by Leehyeonjin93** [dellytools/delly#155]
Hi,
I ran 15 samples to use delly2.
but only 2 samples stoped and I got error message like this;

[2019-Apr-29 19:19:53] SV annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
********./0.run.delly.sh: line 24: 40933 Bus error               (core dumped) $delly_sv call -x ~/Programs/delly/excludeTemplates/human.hg19.excl.exChr.tsv -o $output_path/$samplename.bcf -g $ref_gen $input_path/$samplename/$samplename.sorted.RGfixed.Rmdup.realign.recal.bam

2 bam files were used for varscan, mosaichunter, haplotypecaller, cnvnator.
I tried again 3 times but got same message.

thank you.

**Comment by tobiasrausch** [comment]
Is this happening with the latest version of delly v0.8.1 ? Previously delly created more I/O which apparently on very busy filesystems in cluster environments created these bus errors in rare occasions. I haven't seen this anymore in v0.8.1.

**Comment by Leehyeonjin93** [comment]
yes.
These are my tool's version.
Delly version: v0.8.1
 using Boost: v1.58.0
 using HTSlib: v1.6

**Comment by tobiasrausch** [comment]
Sorry for the long delay. We recently used Delly on >3,000 WGS samples and I couldn't reproduce this error. You didn't edit the Delly Makefile I suppose? The "-O3 -fno-tree-vectorize" is crucial because of htslib cigar memory alignment. I also bumped now the htslib version to the latest release 1.9. Maybe that helps in your case, I am not sure. I am using now htslib v1.9 and boost v1.65.

**Comment by Leehyeonjin93** [comment]
It works now, thank you.
