### ISSUE TITLE
Can i use normal bam for Germline SV with matched-normal ?

### ISSUE THREAD

**Issue by a00101** [dellytools/delly#164]
I have matched WGS sample (tumor-normal).
Do i use only normal bam for germline SV ? 
Is there any process for specific matched-normal  ?

Thank you in advance.

**Comment by tobiasrausch** [comment]
The default Delly germline calling workflow assumes that you have >100 WGS samples. If you have only a few tumor-normal pairs then you could improve your germline calling by calling the tumor and normal jointly. You then filter for het. or hom. alt. germline calls that have at least 1 read-pair/split-read support in the tumor. That usually works because tumor purity <<100% and thus, even if the tumor lost the germline variant carrying allele you can still see support due to normal cell contamination in the tumor. The tumor sample is in a sense an independent observation of SV calls that allows you to confirm/reject germline SV calls.
