### ISSUE TITLE
stuck at the "SV annotation" step

### ISSUE THREAD

**Issue by YonkoBigMom** [dellytools/delly#169]
Hi,

I am using the dockerized version of delly (v0.8.1). I am testing a pair of WGS (Novaseq, 151bp PE reads, 360bp fragment length, and 100x coverage). The bam files are mapped with bwa mem, marked duplicated with samblaster, sorted, and indexed. The delly command is basic: 

`delly call -o delly_output/sv.bcf -g reference/human_g1k_v37.fasta -x reference/human.hg19.excl.tsv  bam/tumor.bam bam/normal.bam`

delly has been stuck at _"SV annotation"_ for almost a day (progress is still at 1%).

[2019-Oct-01 18:24:13] Paired-end and split-read scanning

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2019-Oct-01 19:58:36] Split-read clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2019-Oct-01 19:58:40] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2019-Oct-01 20:02:56] Split-read assembly

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2019-Oct-01 21:43:53] Generate REF and ALT probes

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2019-Oct-01 21:45:01] SV annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*

What are some of the potential problems and how to fix it please?

**Comment by tobiasrausch** [comment]
Hi,

For deep coverage samples at 100x for tumor and normal the most time
consuming step will be indeed the SV annotation (SV genotyping). This step
is exhaustive and interrogates every read overlapping putative SV
breakpoints so that Delly can yield accurate read counts for
reference-supporting and alternative allele-supporting reads and
paired-ends. If this step doesn't finish within a day then it could also be
that your input data needs some upstream filtering (trimming poor quality
bases or trimming remaining adapter sequences). For these sequencing
related problems, you can run Alfred
<https://github.com/tobiasrausch/alfred> and upload the QC JSON file at
https://www.gear-genomics.com/alfred/ or send it to me via email. Then I
can check if you have lot's of inter-chromosomal paired-ends, a high
sequencing error rate, excessive amounts of soft-clips or other BAM related
problems.

Thanks, Tobias
