### ISSUE TITLE
Germline SV filter with one or a few samples

### ISSUE THREAD

**Issue by BaiqiFu** [dellytools/delly#177]
Hello!

I knowed apply the germline SV filter which requires at least 20 unrelated samples, but sometimes only one or a few samples(<20), how to filter in this case?

When there is only one sample, no output if forced use germline SV filter.

I tried some methods:

1) delly filter (output 28 SVs)
delly filter -f germline -p -m 300 -q 0 -e 0 -u 0 -o test_filter.bcf test_call.bcf

2) bcftools view (output 135 SVs)
bcftools view -f "PASS" --min-ac 1:nref --min-alleles 2 --max-alleles 2 --exclude-uncalled -O v -o test_filter.vcf test_call.bcf

3) delly filter and bcftools view (opuput 28 SVs)
delly filter -f germline -p -m 300 -q 0 -e 0 -u 0 -o test_filter.bcf test_call.bcf
bcftools view -f "PASS" --min-ac 1:nref --min-alleles 2 --max-alleles 2 --exclude-uncalled -O v -o test_filter.vcf test_filter.bcf

Could you please look into my issue and tell me what should I do.
Thank you!

[test_call.bcf.gz](https://github.com/dellytools/delly/files/4024639/test_call.bcf.gz)

**Comment by tobiasrausch** [comment]
As written in the [README](https://github.com/dellytools/delly) the germline filter requires many samples because it compares the genotypes across samples for a given SV. If you have only one sample you probably want to check overlap to common SVs from gnomAD to identify private SVs and use QUAL == PASS and maybe INFO:PRECISE calls only.
