### ISSUE TITLE
The results of overlapping inversions from Delly

### ISSUE THREAD

**Issue by r22616890** [dellytools/delly#178]
Hi,
I am using Delly to detect inversions in the genome. I used quality filtration to filter out the "LowQual" inversions. Then, I chose "Precise" to increase the credibility of my output. However, there were still some overlapping inversions in the same individual. I think there might be some false-positive results.

The following are my results:
![123](https://user-images.githubusercontent.com/49189033/71873544-5e789580-315a-11ea-8fcc-540a07c5a9f2.jpg)

Here are my questions:
1. Is it possible that the SR is not equal to 0 while PE is equal to 0? (I thought that the PE is easier to be found than SR)
2. How can I distinguish the false positive in my output?

I am appreciated for any suggestions. Thank you for your time.

Best,
Ting

**Comment by tobiasrausch** [comment]
Hi Ting,

A simple inversion gives rise to two overlapping paired-end inversion signatures (head-to-head, 5to5 and tail-to-tail, 3to3). This is encoded in the delly output as INFO:CT. For instance, INV00003559 and INV00003560 could be a simple inversion because the CT values are complementary (3to3 and 5to5) and the breakpoints are very close to each other. It's usually best to inspect these inversion calls in IGV and visualize the paired-ends.

> Is it possible that the SR is not equal to 0 while PE is equal to 0?
Yes, the latest delly version also calls SVs from split-reads only then PE=0 and SR>0

> How can I distinguish the false positive in my output?
For inversions, that's very tough because inversions are often embedded in repeats. For a single sample, I would indeed filter for PASS and solid PE and SR support at good mapping quality (MAPQ > 30 or SRMAPQ > 30, respectively).
