### ISSUE TITLE
Sample layout has a non-default paired-end layout

### ISSUE THREAD

**Issue by dominiquems** [dellytools/delly#193]
Hello, 

Similar to problem [#137](https://github.com/dellytools/delly/issues/137) I received the warning `Warning: Sample has a non-default paired-end layout! File: <filename>
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.` while running `delly call`. When the run was done, a median and mad of 0 were also reported. However, I am quite unsure what the issue is as these samples were pre-processed similar to samples that were successfully analyzed. 

I also ran `alfred qc` to check out the insert size distribution of the BAM file, but I'm not sure if anything is off there. I will try to attach the results in a comment.

Is there anything that I can do to solve this issue, or is my data not fit? 
One of the samples that gave this warning is obtained from [NCBI SRA](https://www.ncbi.nlm.nih.gov/sra/?term=SRR071591).

**Comment by dominiquems** [comment]
The alfred qc json: [qc_nil.json.gz](https://github.com/dellytools/delly/files/4579297/qc_nil.json.gz)

**Comment by tobiasrausch** [comment]
If you upload the Alfred QC JSON file at [https://www.gear-genomics.com/alfred/](https://www.gear-genomics.com/alfred/) you can see in the insert size distribution a clear double-peak:

![isize](https://user-images.githubusercontent.com/5946458/81074121-dd06f900-8ee8-11ea-9505-20b4b70cc860.png)

The second peak at ~3kbp insert size is due to long-insert paired-ends (mate-pairs) that have an R- orientation instead of the default R+ orientation. Delly requires R+ so you need to flip R- reads to R+ and deplete short insert paired-ends.

**Comment by dominiquems** [comment]
Thanks for the help, I will look into this!
