### ISSUE TITLE
Support for genotyping low coverage single cell data

### ISSUE THREAD

**Issue by amcpherson** [dellytools/delly#194]
I would like to use delly to call SVs in low coverage single cell whole genome data.  The data would be on the order of a few hundred to one thousand cells, 0.01-0.1X coverage per cell.  Two possible strategies are to try to call SVs with each cell as its own 'sample', or to call on a merged bam and do genotyping on predicted SVs per cell.  Any advice would be appreciated.

**Comment by tobiasrausch** [comment]
Calling by cell will likely fail because Delly requires for discovery at least two supporting paired-ends or split-reads. I would indeed suggest to merge the cells, call on the merged BAM and then genotype individual cells. The genotypes will likely be unreliable for single-cells and thus, you probably want to inspect paired-end and split-read support for REF and ALT directly (FORMAT:DR, RR and DV, RV, respectively).

**Comment by funnell** [comment]
I tried the suggested approach, using a vcf output from lumpy-sv computed on merged cell "pseudobulk" bam, and genotyping on a single cell bam using delly. The read counts were quite different than those reported by lumpy-sv and svtyper. Most of the events weren't included in the genotyping bcf.

**Comment by tobiasrausch** [comment]
Sorry, I meant calling the merged cells with delly and then also genotyping in single-cells with delly.

**Comment by tobiasrausch** [comment]
I will close this for the time being. I think calling SVs on sparse single-cell data requires separate SV calling tools.
