### ISSUE TITLE
Small test dataset required

### ISSUE THREAD

**Issue by stephanflemming** [dellytools/delly#202]
Hi,

we are working on a wrapper of delly for the Galaxy toolshed. Therefore I need a small (~ 1MB) test dataset (genome, two bams) for some tests that need to be implemented within the script. I tried a couple of files, but delly doesn't produce a result due to an error like 

`Sample has not enough data to estimate library parameters! File: ...`

Can you provide such a dataset?

Issue and PR can be found [here](https://github.com/galaxyproject/tools-iuc/pull/3139) and [here](https://github.com/dellytools/delly/issues/202).

Thanks in advance!
Stephan

**Comment by tobiasrausch** [comment]
Hi Stephan,

I usually just execute `delly --help` to test if the installation worked, as in the [delly bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/delly/meta.yaml#L29-L31).

If you need a full example with BAM file and FASTA reference then this needs to be sufficiently large because delly estimates the insert size distribution, read length and error rate. Here is a "small" example (~30Mbp): [example.tar.gz](ftp://ftp-exchange.embl-heidelberg.de/pub/exchange/rausch/outgoing/delly/example.tar.gz)

`tar -xzf example.tar.gz && cd example/ && delly call -g DEL.fa DEL.bam`

Best wishes, Tobias

**Comment by stephanflemming** [comment]
Thank you. I finished a first version of the wrapper.

Just a small question, is the module `delly rd` that is described [here](https://github.com/dellytools/delly#read-depth-profiles) still available?

Thank you,
Stephan

**Comment by tobiasrausch** [comment]
Thanks, `delly rd` is a new mode. Currently just GC and mappability corrected read-depth profiles. This will be available in the next delly release but command-line parameters may still change quite a bit. Fine if that's not readily available in Galaxy.

**Comment by mdb571** [comment]
> If you need a full example with BAM file and FASTA reference then this needs to be sufficiently large because delly estimates the insert size distribution, read length and error rate. Here is a "small" example (~30Mbp):
> 
> `wget ftp://ftp-exchange.embl-heidelberg.de/pub/exchange/rausch/outgoing/delly/example.tar.gz`
> 
> `tar -xzf example.tar.gz && cd example/ && delly call -g DEL.fa DEL.bam`

@tobiasrausch  Hi, I would also like to use this sample data for writing autopkgtest for delly package in [Debian](https://salsa.debian.org/med-team/delly). So for including this I would require the license for the provided data so that I may use them in Debian.

Thanks

**Comment by tobiasrausch** [comment]
Thanks. I provide now a simulated example in the delly repository: [https://github.com/dellytools/delly/tree/main/example](https://github.com/dellytools/delly/tree/main/example)

`delly call -o sr.bcf -g example/ref.fa example/sr.bam`
