### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by hellebaa** [dellytools/delly#211]
I have a callset based on merged calls from Delly and Pindel, merging was done using SURVIVOR. Now I wish to genotype all my individuals using this callset, but it fails, giving me out of memory as an error. I am running this on a supercomputer and I am sure memory is not an issue here. This is my code: 

delly call -g gadMor3.fasta -v sample_merged_LG05_sorted.bcf -o LG05.genotypes.bcf LOF1408Z27.aln.marked.duplicate.bam

Bamfiles were generated using bwa-mem and are sorted, marked duplicates and indexed. Any suggestions?

**Comment by tobiasrausch** [comment]
It's likely an issue with the input VCF. The VCF specification is still changing with respect to SVs and some fields that are required by delly are not outputted by other SV callers or SV merging tools. Because of that, genotyping other tool's SV calls often fails. If you can share the input VCF I am happy to take a look why the genotyping fails.

**Comment by tobiasrausch** [comment]
I guess I cannot really help with this if the data has privacy restrictions. Please email me if that's something I can help with.
