### ISSUE TITLE
Starting from which version does Delly2 specify

### ISSUE THREAD

**Issue by davidroberson** [dellytools/delly#272]
We are trying to figure out when Delly2 was upgraded from Delly.  Was this many years ago?

Thank you.

**Comment by tobiasrausch** [comment]
A couple years back, we had the plan to update the initial delly publication because many new features were implemented over the years.  This never materialised as a manuscript but in consortia we started calling it delly2. Anyway, it really doesn't matter, you can refer to the tool as delly or delly2 either way is fine with me.

**Comment by davidroberson** [comment]
thank you.  Delly = Delly2.
