### ISSUE TITLE
Germline SV calling (Questions)

### ISSUE THREAD

**Issue by Taalouane** [dellytools/delly#287]
Hi,

I'm working with Human WGS 35X paired-end (in 25 WGS unrelated)

I followed the protocol as described in readme "**Germline SV calling**".

The number of variants (>= 50bp) found after the "**Merge all genotyped samples**" step (calculated with SURVIVOR)
```
Tot	DEL	DUP	INS	INV	TRA
46441	16103	7121	298	2104	20815
```
The number of variants (>= 50bp) found after the "**Apply the germline SV filter**" step (calculated with SURVIVOR)
```
Tot	DEL	DUP	INS	INV	TRA
20413	8789	1011	0	849	9764
```
As you see:
- A very high number of variants have been filtered. 
- No insertion variants have been identified.

Some filtered/deleted variants have been checked and found/visualized in IGV/samplot

Do you think the filtered variants are not germline variants? On which criteria are these variants filtered? Do you have any suggestions ?

Best,
Tarek

**Comment by tobiasrausch** [comment]
> No insertion variants have been identified.
Delly requires spanning reads that completely contain the inserted sequence. That's very conservative, but in our experience, insertion calling is just too error-prone otherwise. For large insertions >50 bp you should really consider using long reads like PacBio HiFi or ONT.

> A very high number of variants have been filtered.
As written in the README, 25 unrelated WGS samples is really on the low end and this causes the germline filter to be quite strict. Delly always needs at least one reliable carrier and non-carrier for each SV site, and the more samples you add, the better this works.

**Comment by tobiasrausch** [comment]
(1) If you have just one sample, you probably want to call SVs using something like `delly call -x hg19.excl -o delly.bcf -g hg19.fa input.bam`.
(2) With delly, BND is solely used for inter-chromosomal translocations and thus, there is no "length".
