### ISSUE TITLE
Using PacBio/pbsv VCF for delly force genotyping (-v)?

### ISSUE THREAD

**Issue by bbimber** [dellytools/delly#382]
Hello,

We have a dataset of SVs created from PacBio data using pbsv. We'd like to take those SVs and use delly to genotype a dataset of Illumina WGS samples at these specific sites. We made a sites-only VCF from the PacBio data and provided this VCF as "-v" for delly call. This command dies with the error "Delly genotyping requires local SV assembly (INFO/CONSENSUS) and breakpoint (INFO/CONSBP) introduced in delly v1.1.7!", which maps to this code:

https://github.com/dellytools/delly/blob/30487896818f213653c45edcd1230a9f2c040092/src/modvcf.h#L291

I assume the problem is that the VCF lack from INFO annotations delly expects. 

My question is: is there a way to use a VCF generated by another caller (pbsv in particular) as the whitelist of delly's forced genotyping?

Thanks for any help.

**Comment by tobiasrausch** [comment]
I am afraid that SV discovery using pbsv and SV genotyping using delly is not going to work. Since delly now supports long-read SV calling you can either:
(a) Call and genotype SVs using long-read data with `delly lr`
(b) Map SV contigs from pbsv to the reference, use `delly asm` to generate an SV site list and then genotype the SVs
I should say that (b) is very much under development so you probably should compile from source and I haven't had time yet to benchmark this properly.

**Comment by bbimber** [comment]
ok, thanks
