### ISSUE TITLE
Question on joint genotyping

### ISSUE THREAD

**Issue by ldorozco** [dellytools/delly#77]
I as wondering if Delly2 does "joint genotyping" of multiple samples, analogous to what GATK does for SNPs? 

Does Delly2 do break-point resolution? For example, if I have a population samples with structural variants in the same region, can Delly2 use that information to try to figure out the boundaries of the structural variant? 

Thank you,

Luz

**Comment by tobiasrausch** [comment]
If you provide to Delly multiple BAMs it indeed pools the data and does joint genotyping. This scales pretty bad and because of that, I frankly prefer the calling by sample, merging and re-genotyping workflow as shown in the README (section "Germline SV calling"). This still works for thousands of samples.

For these kind of usage questions you might want to join the delly-users mailing list:

https://groups.google.com/forum/#!forum/delly-users

Best, Tobias
