### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by royfrancis** [dellytools/delly#86]
When I run `delly call`, I find that the `-t` options are `SV type (DEL, DUP, INV, BND, INS)`. What is `BND`? I thought there was `TRA`, but seems like not. And what is `-s`? How do I specify it? Is the `-n` argument only applicable when `-t DEL`? Where can I find the detailed documentation for all these arguments?

**Comment by tobiasrausch** [comment]
TRA was recently replaced by BND because of the VCF spec. Delly uses BND only for inter-chromosomal translocations (the former TRA type).

-s only affects the deletion calling. It specifies a cutoff for the insert size (median insert size + s * median absolute deviation of your insert size distribution). If you have a very wide insert size distribution you may have to increase -s . To plot your insert size distribution and all kinds of other alignment statistics we developed [alfred](https://github.com/tobiasrausch/alfred). Static binaries for alfred are [here](https://github.com/tobiasrausch/alfred/releases).

Many Delly usage questions are discussed in the [delly-users](https://groups.google.com/forum/#!forum/delly-users) mailing list.
